### ISSUE TITLE
There is a ERROR in your code~

### ISSUE THREAD

**Issue by novioleo** [drewgarrido/pidish_slicer#2]
in function transform_scene,the tmp_scene need to be deepcopied~
you use copy,will make some error when there are some angles in main function.

**Comment by drewgarrido** [comment]
You are probably right. By curiosity, what kind of problem are you seeing? In my testing, I did not notice a problem with using copy, so I didn't bother with deepcopy().

**Comment by novioleo** [comment]
@drewgarrido if there are multi angles try to find the best,the scene value will change.you changed the tmp_scene due to the shallow copy.

**Comment by drewgarrido** [comment]
Fixed in the latest push.
